#!/usr/bin/env bash

SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

rg -H \
  -e "^module \S*" \
  -e "^type \S*" \
  -e "^data \S*"  \
  -e "^class .*" \
  -e "^newtype \S*" \
  -e "^[a-z][A-Za-z0-9]+( ::|$)" \
  ${@:-.spago/**/*.purs lib/**/*.purs} \
  | python3 "$DIR/taggert.py" > tags
